import {
  Download,
  FileText,
  Hash,
  RefreshCcw,
  ShieldCheck,
} from "lucide-react";
import { fetchAuditReport } from "@/lib/api";

export default async function AuditPage({ params }: { params: { id: string } }) {
  const report = await fetchAuditReport(params.id);

  const stats = [
    { label: "Bidders", value: report.bidder_count },
    { label: "Criteria", value: report.criteria_count },
    { label: "Verdicts", value: report.verdict_count },
    { label: "Needs Review", value: report.needs_review_count },
  ];

  return (
    <main className="mx-auto max-w-5xl px-6 py-8">
      <div className="mb-6">
        <h1 className="text-lg font-bold text-gray-950">Audit Report</h1>
        <p className="text-xs text-gray-500">
          Replayable report metadata for procurement review and sign-off.
        </p>
      </div>

      <section className="mb-6 rounded-lg border border-gray-200 bg-white p-5 shadow-card">
        <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase text-gray-400">Tender</p>
            <h2 className="mt-1 text-base font-bold text-gray-950">{report.tender_title}</h2>
            <p className="mt-1 text-sm text-gray-500">{report.procuring_department}</p>
          </div>
          <div className="inline-flex w-fit items-center gap-1.5 rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-800">
            <ShieldCheck className="h-3.5 w-3.5" />
            Signed-ready
          </div>
        </div>

        <div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4">
          {stats.map((item) => (
            <div key={item.label} className="rounded-md border border-gray-200 bg-gray-50 p-3">
              <p className="text-lg font-extrabold text-gray-950">{item.value}</p>
              <p className="text-xs text-gray-500">{item.label}</p>
            </div>
          ))}
        </div>

        <div className="rounded-md border border-gray-200 bg-gray-50 p-3">
          <p className="mb-2 flex items-center gap-1.5 text-xs font-semibold uppercase text-gray-500">
            <Hash className="h-3.5 w-3.5" />
            SHA-256 Content Hash
          </p>
          <p className="break-all font-mono text-xs text-gray-700">{report.content_hash}</p>
        </div>
      </section>

      <section className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3">
        <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-card">
          <p className="text-xs font-semibold uppercase text-gray-400">Generated By</p>
          <p className="mt-1 text-sm font-semibold text-gray-950">{report.generated_by}</p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-card">
          <p className="text-xs font-semibold uppercase text-gray-400">Replay ID</p>
          <p className="mt-1 text-sm font-semibold text-gray-950">{report.replay_id}</p>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-card">
          <p className="text-xs font-semibold uppercase text-gray-400">Model</p>
          <p className="mt-1 text-sm font-semibold text-gray-950">
            {report.model_versions.join(", ")}
          </p>
        </div>
      </section>

      <div className="flex flex-col gap-3 sm:flex-row">
        <a
          href={report.pdf_uri}
          className="inline-flex flex-1 items-center justify-center gap-2 rounded-md bg-brand px-4 py-3 text-sm font-semibold text-white hover:bg-brand-dark"
        >
          <Download className="h-4 w-4" />
          Download Audit PDF
        </a>
        <button className="inline-flex flex-1 items-center justify-center gap-2 rounded-md border border-brand px-4 py-3 text-sm font-semibold text-brand hover:bg-brand-bg">
          <RefreshCcw className="h-4 w-4" />
          Replay Evaluation
        </button>
        <button className="inline-flex flex-1 items-center justify-center gap-2 rounded-md border border-gray-300 px-4 py-3 text-sm font-semibold text-gray-700 hover:bg-gray-50">
          <FileText className="h-4 w-4" />
          View JSON
        </button>
      </div>
    </main>
  );
}
